### ISSUE TITLE
Website live link

### ISSUE THREAD

**Issue by Sreekar-Shodhan** [TRohit20/Blogs-Website#1]
Can I please get the website live link if its still live!!. I have few ideas to implement and also try to apply tailwind CSS in this project

**Comment by TRohit20** [comment]
Hey @Sreekar-Shodhan, That's great. The website is not live currently. If you'd like to contribute, feel free to fork the repo, make the changes, add features you want and open a pull request :)

You can fork, clone and run the website locally too. Good luck :)

**Comment by Sreekar-Shodhan** [comment]
okay thank you. Sorry I didnt see this msg but yeah sure will work on this
