### ISSUE TITLE
life.blog() logo should not be clickable

### ISSUE THREAD

**Issue by Bhanu-code** [TRohit20/Blogs-Website#4]
**life.blog() logo should not be clickable**
![Capture](https://user-images.githubusercontent.com/77599001/223015338-c6fdea83-d7e8-410d-b49a-bacd380767fd.JPG)

**Comment by TRohit20** [comment]
I made it clickable intentionally @Bhanu-code . It is kind of a practise with websites where the logo of the website to used to easily get back to the main/home page.

**Comment by Bhanu-code** [comment]
I think a home button will be more relevant form that

**Comment by TRohit20** [comment]
You can do it either way IMO.

**Comment by Bhanu-code** [comment]
> I think a home button will be more relevant form that
