### ISSUE TITLE
Add firebase backend

### ISSUE THREAD

**Issue by Bhanu-code** [TRohit20/Blogs-Website#5]
add the backend functionality for blogs.

**Comment by Bhanu-code** [comment]
assign me this issue, I will add the firebase for backend

**Comment by TRohit20** [comment]
I would love to, Just a quick question though, what are the features that you intend to add? Authentication, Post creation, storage etc ?

**Comment by Bhanu-code** [comment]
> I would love to, Just a quick question though, what are the features that you intend to add? Authentication, Post creation, storage etc ?

Authentication using with google, Facebook, twitter and sign up sign, blog post storage with firestore, further migration to realtime db if needed.. Etc.

**Comment by TRohit20** [comment]
Awesome, Assigning the Issue to you so you can work on it.

**Comment by TRohit20** [comment]
Good luck!

**Comment by Bhanu-code** [comment]
> Awesome, Assigning the Issue to you so you can work on it.

Thank you
